-- Kekki — migration 005a: extend clusters.kind to accept 'evaluator' (D22).
--
-- The intake evaluator (D22 mode 3) starts a one-shot review session against
-- a user-private cluster sampled across the 18 ABIM systems. The session_id
-- is what feeds initFromEvaluatorSession() — the cluster's only job is to
-- give finishSession() a kind it can branch on.
--
-- This is a constraint-only change. No table or column added.

alter table public.clusters drop constraint clusters_kind_check;
alter table public.clusters add constraint clusters_kind_check
  check (kind in ('manual','ephemeral_topic','evaluator'));

comment on column public.clusters.kind is
  'D22: cluster provenance. manual = human-curated. ephemeral_topic = '
  'auto-generated by deterministic planner from a weak topic. evaluator = '
  'one-shot calibration session (intake mode 3) that seeds initial '
  'competence per topic.';
